site_name: Griptape Docs
plugins:
  - glightbox
  - search
copyright: "&copy; Griptape, Inc."
extra:
  analytics:
    provider: google
    property: G-QM8EDPSCB6
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/gnWRz88eym
    - icon: fontawesome/brands/github
      link: https://github.com/griptape-ai/griptape/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/griptape/
theme:
    name: material
    custom_dir: docs/overrides
    logo: assets/griptape-logo.png
    palette:
      # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - content.code.copy
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.top
        - navigation.footer
        - announce.dismiss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - def_list
nav:
- Home:
    - Overview: "index.md"
    - Contributing: "contributing.md"
    - FAQ: "faq.md"
- Griptape Framework:
  - Overview: "griptape-framework/index.md"
  - Structures:
    - Pipelines: "griptape-framework/pipelines.md"
    - Agents: "griptape-framework/agents.md"
    - Workflows: "griptape-framework/workflows.md"
    - Serialization: "griptape-framework/serialization.md"
  - Prompt Drivers:
    - Overview: "griptape-framework/prompt-drivers/index.md"
    - OpenAI: "griptape-framework/prompt-drivers/openai.md"
    - Cohere: "griptape-framework/prompt-drivers/cohere.md"
    - Hugging Face Hub: "griptape-framework/prompt-drivers/hugging-face-hub.md"
    - Hugging Face Pipeline: "griptape-framework/prompt-drivers/hugging-face-pipeline.md"
  - Misc:
    - Memory: "griptape-framework/memory.md"
    - CoT and Tools: "griptape-framework/cot-and-tools.md"
    - Building Custom Tools: "griptape-framework/custom-tools.md"
- Griptape Tools:
    - Overview: "griptape-tools/index.md"
    - Official Tools:
      - AwsCli: "griptape-tools/official-tools/aws-cli.md"
      - Calculator: "griptape-tools/official-tools/calculator.md"
      - EmailClient: "griptape-tools/official-tools/email-client.md"
      - SqlClient: "griptape-tools/official-tools/sql-client.md"
      - WebScraper: "griptape-tools/official-tools/web-scraper.md"
      - WebSearch: "griptape-tools/official-tools/web-search.md"
      - RestApi: "griptape-tools/official-tools/rest-api.md"
